version: '3.8'

services:
  prod_count:
    build:
      context: "."
      dockerfile: counter_image/Dockerfile
    image: phaustin/counter:dec21
    container_name: counter_prod
    ports:
        - "127.0.0.1:8000:8000"
    networks:
      - tests
    command: [ "gunicorn", "--workers=5", "--threads=1", "-b 0.0.0.0:8000", "counter.do_count:server"]

  dev_count:
    depends_on:
     - prod_count
    image: phaustin/counter:dec21
    container_name: counter_dev
    volumes:
     - "./counter:/home/jovyan/counter"
    ports:
        - "127.0.0.1:8050:8000"
    networks:
      - tests
    command: [ "gunicorn", "--workers=5", "--threads=1", "-b 0.0.0.0:8000", "counter.do_count:server"]

    
networks:
  tests:
