name: dbdev
channels:
  - eoas_ubc
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - importlib_resources
  - dash
  - pip
  - gunicorn
  - conda-lock
# conda-lock -f environment_linux.yml -p linux-64
